### ISSUE TITLE
3 letter acronyms

### ISSUE THREAD

**Issue by ctron** [m-czernek/acrobot#15]
It looks like bot isn't getting triggered for 3 letter acronyms.

**Comment by m-czernek** [comment]
Hi,

thank you very much for your issue report. Can you be a bit more specific? What three letter acronym does Acrobot not respond to? A cursory testing in prod:

![image](https://user-images.githubusercontent.com/16302538/85857997-21ad6300-b7bb-11ea-8a23-47503f0e2e1d.png)

**Comment by ctron** [comment]
e.g. `PNC`:

![image](https://user-images.githubusercontent.com/202474/86011987-b31c0f80-ba1d-11ea-8418-0911238f8646.png)

**Comment by m-czernek** [comment]
Looks like intended behavior.

If you send a personal message to Acrobot (that means only you can see the communication, it's not in any room), Acrobot responds directly. So, the expected message is just `PNC` and the expected response is the explanation.

If you are in a room, Acrobot does not listen to all messages. You actively have to tag Acrobot and then, Acrobot has access only to your message and no other messages in the room. In a room, you have to send `@Acrobot PNC` and you get a response only when the `@Acrobot` is a link. 

Does that make sense?

**Comment by ctron** [comment]
Hm, reviewing the chat logs: Indeed, every time the bot got asked directly.

> Does that make sense?

Yes, it does :grinning: Sorry for the troubles.
