### ISSUE TITLE
Disable the check of author email when updating/removing an acronym

### ISSUE THREAD

**Issue by mohanboddu** [m-czernek/acrobot#22]
The [check](https://github.com/m-czernek/acrobot/blob/master/src/main/java/com/redhat/messages/MessageHelper.java#L78) is not ideal when we want to update the acronym if we dont know the person who added it in first place or left the company. This needs to be fixed.

**Comment by m-czernek** [comment]
Hi Mohan,

Right now, the technical decision is not to enable you to delete the explanation of other contributors, only your own. Simply removing the check, therefore enabling anyone to delete any explanation from anyone else, is definitely not the way I'd like to go. 

I am also very wary of enabling folks to see who added what as that can open a whole another can of worms.

What exactly is the problem you are trying to solve?

**Comment by mohanboddu** [comment]
Hello Marek,

This is what happened:

```
@Acrobot  CPE
Acrobot, Bot, Yesterday 10:09 AM
...
Community Platform Enablement (Merger of Fedora Infra and CentOS Infra teams)
...
```

This was wrong as CPE (my team) stands for `Community Platform Engineering`, so we tried to remove it:

```
@Acrobot !CPE=Community Platform Enablement (Merger of Fedora Infra and CentOS Infra teams) => Community Platform Engineering (Joint Fedora and CentOS Infrastructure DevOps)

Acrobot, Bot, Yesterday 10:12 AM
You cannot update acronyms that you did not save. Aborting!
```

But we dont know who added it in first place, so we couldn't remove/update it, hence I raised this ticket.

I understand that you dont want to allow anyone randomly update/remove acronym definitions, but that also means we cant remove/update the one's that are incorrect. Can we create a ticket here for such cases?

FYI, since we couldn't update it, we added the correct one, but now we have two of them, one of them is correct the other one is incorrect.

```
@Acrobot cpe
Acrobot, Bot, Yesterday 10:14 AM
...
Community Platform Engineering (Joint Fedora and CentOS Infrastructure DevOps Team)
Community Platform Enablement (Merger of Fedora Infra and CentOS Infra teams)
...
```

**Comment by m-czernek** [comment]
Got it.

So,

> Can we create a ticket here for such cases?

Yes. This is one of the reasons why my name is public. You can ping me directly, you can file issues, you can send me an email. 

> But we dont know who added it in first place, so we couldn't remove/update it, hence I raised this ticket.

I have checked the DB, contacted the person, and with the person's approval dropped the original explanation. Current status:

```
Acrobot, Bot, 3 min
...
Community Platform Engineering (Joint Fedora and CentOS Infrastructure DevOps Team)
```

This happens once in a while. I have been thinking about a voting system, where you as an individual cannot drop other people's explanation, but if you can get, say, 5 votes, you can override the check. But because tickets like these are so rare (where someone requests me to delete something), I haven't implemented something similar just yet.

**Comment by mohanboddu** [comment]
Thanks Marek for fixing this issue.

> This happens once in a while. I have been thinking about a voting system, where you as an individual cannot drop other people's explanation, but if you can get, say, 5 votes, you can override the check. But because tickets like these are so rare (where someone requests me to delete something), I haven't implemented something similar just yet.

Yeah, as long as people can find a way to fix things, either by opening a ticket or something else, it is fine. But yeah, voting seems to be an appropriate solution.

Thanks again.

Closing the ticket as the issue is fixed.
