### ISSUE TITLE
RFE: please add ability to delete entries

### ISSUE THREAD

**Issue by pcfe** [m-czernek/acrobot#3]
it would be useful to have the ability to delete an entry (for those times one makes a typo)

User story;
Patrick tries to enter 2 meanings for TMI but typoes on one of the two.
Patrick would like the ability to correct the one wrong entry.
Deleting the wrong entry (one of N) and then adding a correct one works just as well.

**Comment by pcfe** [comment]
suggestion for picking one of N meanings when deleting or correcting;
have the user specify the whole wrong line. This should allow for copypasta

**Comment by m-czernek** [comment]
Hi @pcfe, 

The RFE is now deployed. It is reasonably tested, but before merging to master, I'd like you to try and test as well. Current syntax:

`!acronym=old explanation=>new explanation` - changes old explanation to a new one
`!acronym=old explanation=>` - deletes given explanation

Note that you can change only acronyms you inputted. 

Any thoughts before I merge the branch?

**Comment by pcfe** [comment]
Hi @m-czernek 

Tested as follows
- delete an entry I created: test passed, entry got deleted as expected
- change an entry I created: test passed, entry got updated as expected
- delete an entry I did *not* create: test passed, deletion was refused
- change an entry I did *not* create: test passed, change was refused

And a big thumbs up for the clear error messages when a user tries to change a entry of someone else. Much appreciated. Too many tools spit out cryptic errors.

Looks good to merge.

**Comment by m-czernek** [comment]
Deployed. Thank you for the RFE. Closing issue as resolved.

**Comment by emonkfu** [comment]
> And a big thumbs up for the clear error messages when a user tries to change a entry of someone else. Much appreciated. Too many tools spit out cryptic errors.

Error messages too clear. Requires no advanced Chaos theory knowledge to understand with my usage or commands. In-depth understanding and visualization of dark matter not required before use of bot.

Please fix.
