### ISSUE TITLE
Acrobot stops responding on GChat

### ISSUE THREAD

**Issue by asaket** [m-czernek/acrobot#36]
Hi, wondering if there is any downtime? It stops responding on GChat. Pls ref the screenshot. Thanks!

<img width="929" alt="Screenshot 2022-12-05 at 10 57 07 AM" src="https://user-images.githubusercontent.com/6190603/205556257-4edea601-df9a-4a13-9f96-855bc732d2ba.png">

**Comment by m-czernek** [comment]
Thank you @asaket for the report. The underlying OCP platform restarted Acrobot's DB pod, and then failed to mount the PVC upon startup. I have restored the service by using a failover DB. Closing this issue as Acrobot is back up; creating a ticket for Red Hat's platform support about the failing DB mount.
