### ISSUE TITLE
Acrobot is not working

### ISSUE THREAD

**Issue by asaket** [m-czernek/acrobot#41]
Hi,

This google chat bot has not been working since past few weeks. I was able to use it regularly before.
Is there any fix in progress?

Thanks,
Ashish | Red Hat

**Comment by m-czernek** [comment]
Hello, I'm no longer at Red Hat. Please ping [Eduardo](https://github.com/ebramirez) who took over the maintenance of acrobot at Red Hat, or [Richard](https://github.com/richardallred) as a backup.
